name: Generate a list of albums added in the MDRP

on: push

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requests module
        run: pip install requests

      - name: Run the script
        run: python -m generate_artists

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: Update file to reflect new albums in library 🥳
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
